// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfTYlh90ClHMWNST9pUHC7wM-u3ug9T04',
    appId: '1:1063160680312:android:5b6bd81f09fcc070d9c28d',
    messagingSenderId: '1063160680312',
    projectId: 'codeair-598fd',
    databaseURL: 'https://codeair-598fd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'codeair-598fd.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtwcDYJhFpt3ruvch_IYwUSzv3-prOxgk',
    appId: '1:1063160680312:web:b538eafeb5bfa5efd9c28d',
    messagingSenderId: '1063160680312',
    projectId: 'codeair-598fd',
    authDomain: 'codeair-598fd.firebaseapp.com',
    databaseURL: 'https://codeair-598fd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'codeair-598fd.firebasestorage.app',
    measurementId: 'G-9MJCB84R09',
  );

}